# Generated by Django 2.1.4 on 2019-01-16 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelContato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=100)),
                ('assunto', models.CharField(max_length=100)),
                ('mensagem', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Contatos',
                'db_table': 'contato',
                'verbose_name': 'Contato',
            },
        ),
    ]
