# Generated by Django 2.1.4 on 2019-01-16 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile')),
                ('cidade', models.CharField(choices=[('PF', 'PASSO FUNDO')], default='', max_length=50)),
                ('bairro', models.CharField(default='', max_length=50)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('desenvolvedor', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=True)),
                ('quantidade_posts', models.IntegerField(blank=True, default=0, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Profiles',
                'db_table': 'profile',
                'verbose_name': 'Profile',
            },
        ),
    ]
