# Generated by Django 2.1.4 on 2019-01-17 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelprofile',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='profile'),
        ),
    ]
